# -*- coding: utf-8 -*-
"""Betas & Ke (MERVAL Index).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SnCROQJRy6yAP_aUJVu4AOtBneV_9QRq
"""

pip install yfinance

import pandas as pd
import datetime as dt
import yfinance as yf
from prettytable import PrettyTable
from sklearn.linear_model import LinearRegression

dt.date.today()

tickers = ['ALUA.BA',	'BBAR.BA',	'BMA.BA',	'BYMA.BA',	'CEPU.BA',	'COME.BA',	'CRES.BA',	'CVH.BA',	'EDN.BA',	'GGAL.BA',	'LOMA.BA',	'MIRG.BA',	'PAMP.BA',	
           'SUPV.BA',	'TECO2.BA',	'TGNO4.BA',	'TGSU2.BA',	'TRAN.BA',	'TXAR.BA',	'VALO.BA',	'YPFD.BA', '^MERV']
data = pd.DataFrame()

for sym in tickers:
    data[sym] = yf.download(sym, start = '2020-01-01', end = dt.date.today(), progress = False)['Adj Close']
data.dropna(axis = 1, inplace = True)
data_ret = data.pct_change().dropna()

idx = '^MERV'

MRP = ((data[idx][-1]/data[idx][0])**(1/(data.index[-1] - data.index[0]).days) - 1) * 100 # Merket Risk Premium
RFR = 0.38 # Risk Free Rate

betas = []
for i in range(data.shape[1]):
  a = LinearRegression().fit(np.array(data_ret[idx]).reshape((-1, 1)), np.array(data_ret.iloc[:,i]).reshape((-1, 1)))
  betas.append(a.coef_)

Ke = []
for j in range(data.shape[1]):
  a = RFR + betas[j] * (MRP - RFR)
  Ke.append(a)

df = pd.DataFrame([betas, Ke])
df = df.T
df.rename(columns = { 0 : 'Beta', 1 : 'Ke'}, inplace = True)
df.index = data.columns
df.drop(idx, inplace = True)

df.iloc[0,0]

x = PrettyTable()
x.field_names = ['Stock', df.columns[0], df.columns[1]]

for k in range(df.shape[0]):
  x.add_row([df.index[k], round(df.iloc[k,0][0][0], 2), round(df.iloc[k,1][0][0], 2)])

x.sortby = 'Ke'
x.reversesort = True
print(x)