# -*- coding: utf-8 -*-
"""Sharpe Ratios (MERVAL Index).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11n7pSNeGjhZhO_kRUOkedstVvFG6kFbH
"""

pip install yfinance

import pandas as pd
import datetime as dt
import yfinance as yf
from math import sqrt
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

dt.date.today()

tickers = ['ALUA.BA',	'BBAR.BA',	'BMA.BA',	'BYMA.BA',	'CEPU.BA',	'COME.BA',	'CRES.BA',	'CVH.BA',	'EDN.BA',	'GGAL.BA',	'LOMA.BA',	'MIRG.BA',	'PAMP.BA',	'SUPV.BA',	'TECO2.BA',	'TGNO4.BA',	'TGSU2.BA',	'TRAN.BA',	'TXAR.BA',	'VALO.BA',	'YPFD.BA']
data = pd.DataFrame()

for sym in tickers:
    data[sym] = yf.download(sym, start = '2020-01-01', end = dt.date.today(), progress = False)['Adj Close']
data.dropna(axis = 1, inplace = True)

data_ret = data.pct_change().dropna()
returns = data_ret.mean() * 252
sigmas = data_ret.std() * sqrt(252)

TPM = 0.38
sharpe_ratios = (returns - TPM) / sigmas
sharpe_ratios = sharpe_ratios.sort_values(ascending = True)

plt.figure(figsize=(18,6))
plt.barh(y=sharpe_ratios.index, width=sharpe_ratios)
plt.title('MERVAL')
plt.ylabel('Tickers')
plt.xlabel('Sharpe Ratio')
plt.xlim(min(sharpe_ratios),max(sharpe_ratios))
plt.show()